### ISSUE TITLE
Need to resurrect the training/events calendar

### ISSUE THREAD

**Issue by archaeogeek** [osgeouk/website#17]
Should be a simple table, nothing fancy, then we can accept pull requests for updates. We'll have to manually prune out of date events/training ourselves but that shouldn't be too onerous

**Comment by walkermatt** [comment]
We could maybe maintain a CSV and use Jerkll to convert to a table (see https://jekyllrb.com/docs/datafiles/). We could then also make the CSV available for direct download.

**Comment by archaeogeek** [comment]
Sorry didn't mean to close! I was thinking of just letting people add a new line to the table but if there are other whizzy ideas then let's investigate

**Comment by walkermatt** [comment]
I've just pushed 6084b106b813cd103520aac610ed35439596d962 which adds a basic training page and a link to it from the home page. Only includes @AstunTechnology courses at the moment, we should  ask on list for others to contribute their courses.

We could also consider expanding the scope of the page to include events as well as training; maybe a csv file and corresponding tables?

**Comment by archaeogeek** [comment]
Nice- can you add a column for event type and then submit an email to the mailing list about it please? Not sure I'll have time to do it today myself but we should do it quickly to avoid accusations of bias.

**Comment by archaeogeek** [comment]
Thanks, all good, the last thing I would do is set the link to the csv in github to open in a new tab with {:target="_newpage"}

**Comment by walkermatt** [comment]
I going to ask about opening in a new tab, it feels unnecessary to me for such a small site?

**Comment by archaeogeek** [comment]
I just thought we should do it for sending people out of the site into github proper. Keep eyes on the site y'know!
