### ISSUE TITLE
Site doesn't support HTTPS

### ISSUE THREAD

**Issue by JamesLMilner** [osgeouk/website#27]
For example: https://osgeouk.com 

It would be good practice to support HTTPS as this is becoming a standard nowadays. Where is the site hosted? We might need to purchase a new SSL certificate.

It might also be possible with LetsEncrypt (free)

**Comment by archaeogeek** [comment]
@JamesMilnerUK the site is hosted on github using github pages. It's a sub-domain of the main osgeo.org. Changing the domain is not on the cards at the moment but I'll see if/how one goes about supporting https for non-github.io sites hosted in this way.

**Comment by archaeogeek** [comment]
@JamesMilnerUK this is not currently possible using github pages. Given that we're now closely integrated and well set up with github, and with the uk.osgeo.org domain, I think we just have to put up with the lack of https until github resolve the problem- see https://github.com/isaacs/github/issues/156 for example.

**Comment by JamesLMilner** [comment]
I see. I had the same problem with a site I maintain. I can recommend https://www.netlify.com/ which also provides free certificates and is very straight forward to use (arguably easier than GH Pages!). If it's something you're interested in I can discuss it with you in more detail.

**Comment by archaeogeek** [comment]
Gitlab does the same thing, that's what I use for other sites, and it integrates with letsencrypt but we'd need to get everyone who contributes to also create accounts on gitlab etc.

**Comment by war59312** [comment]
It's possible with CloudFlare....

How to serve a custom HTTPS domain on GitHub Pages with CloudFlare: *FREE*, secure and performant by default: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b

**Comment by archaeogeek** [comment]
@war59312 Nice find! There might be complications as uk.osgeo.org is obvs a sub-domain, and we don't have control over the wider osgeo.org domain but I'm willing to try this out, possibly later this week. I'll re-open this issue so I don't forget :-)

**Comment by archaeogeek** [comment]
@war59312 @JamesMilnerUK  Update: fell on the first hurdle registering uk.osgeo.org with cloudflare- it doesn't allow you to register it because it's a sub-domain and not a full domain. I'll investigate further but I think we'll possibly have to sit tight and wait for github to provide the option for https.

**Comment by war59312** [comment]
Could always forward requests from uk.osegeo.org to a new domain ?

**Comment by archaeogeek** [comment]
The answer is still no, I'm afraid. It's not about the technicalities so much as the management of OSGeo:UK and it's assets. We have made a conscious decision to keep things as simple as possible with no dependencies on any one person, or additional service. This is based on the experience of regaining ownership of key components when the person involved was no longer interested, so it's not going to change any time soon!

**Comment by war59312** [comment]
No worries, thanks. Was just curious. I understand, security first. I like it.

Have a great weekend.
