### ISSUE TITLE
Incorrect Training Details in http://uk.osgeo.org/training.html

### ISSUE THREAD

**Issue by AstunEoghan** [osgeouk/website#43]
The following event has the wrong title:
Current: PostGIS DBA Essentials | 17-18 July 2018 | Astun Technology | Bristol

Correct: PostGIS Essentials | 17-18 July 2018 | Astun Technology | Bristol

This event does not exist:
PostGIS Essentials | 28 June 2018 | Astun Technology | Birmingham

**Comment by archaeogeek** [comment]
Fixed by https://github.com/osgeouk/website/commit/a33ad48fedd43e2c79d39e740e6a641be1ad8950
