### ISSUE TITLE
Add room sizes to titles in timetable

### ISSUE THREAD

**Issue by archaeogeek** [osgeouk/website#8]
Solent 150
Test 70 32 for codesprint)
Hamble 16 (20 for hack)
Avon 8 (this is our breakout room)
Itchen 12
Meon 8

**Comment by barryrowlingson** [comment]
Fixed except there's no mention of Avon in the timetable...

**Comment by archaeogeek** [comment]
Yeah it's just the breakout room so doesn't need to be included.
